<?php
	include 'library.php';

  Entete( 'grenadin', 'fre' );
?>

<h1 style="text-align:center; color: blue">CHRONIQUE (OBJECTIVE) D'UNE CROISIERE ORDINAIRE (ou UNE SEMAINE CHEZ LES CARTES POSTALES.)</h1>
<br/>
L'EQUIPAGE.<br/>
The skipper	Jos&eacute;<br/>
The others :<br/>
<table><tr><td style="width:50px"></td><td>
Cathy, dans le r&ocirc;le de "La blonde" (je suis petite)<br/>
Magaly,	"Quart de tour" (j'ai sommeil)<br/>
Christophe M., "Honn&ecirc;tement" (pour le coup)<br/>
Christophe R., "Slip de bain" (c'est pas Meum's time ?)<br/>
Guillaume, "Maxikakou" (j'ai la p&ecirc;che)<br/>
Micka&euml;l, "Le Breton" (j'ai la gerbe)<br/>
</td></tr></table>

<table style='width:100%'><tr><td><h2>28/01/1997 : Pointe du Bout =&gt; Marigot Bay (Ste-Lucie)</h2></td><td align="right"><a class="travel2" href="#top"><img style="border:0px"  src="images/top_blue.png" alt="top"/></a></td></tr></table>
<p>
Le d&eacute;part est donn&eacute; &agrave; 13 heures, apr&egrave;s avoir aval&eacute; un sandwich, ce qui est peu pour la travers&eacute;e. Le Diamant laiss&eacute; sur b&acirc;bord, les premi&egrave;res vagues commencent &agrave; d&eacute;ferler sur l'avant du bateau, serr&eacute;es, rapproch&eacute;es. Pour le moment, c'est fun. Magaly dort d&eacute;j&agrave; (pr&eacute;cision de l'int&eacute;ress&eacute;e : elle ne dort pas "je suis allong&eacute;e pour ne pas &ecirc;tre malade").<br/>
&Agrave; peine est on sorti de la Baie des Flamands que l'annexe tombe presque &agrave; la flotte. On la rattrape et on la ram&egrave;ne sur le filet o&ugrave; on l'attache comme on peut. &Ccedil;a secoue de plus en plus et &ccedil;a commence &agrave; ne plus &ecirc;tre tr&egrave;s marrant. Guillaume prends l'air pour &eacute;viter un appatage de poissons pr&eacute;coces, Cathy comate (certainement l'effet des cinq nautamines !), pour les Christophes, jusquE l&agrave;, &ccedil;a va sans probl&egrave;mes, le skipper skippe et le Breton va bien, forc&eacute;ment, un Breton(c), c'est construit pour la mer. Quoique, c'est plus ce n'est que c'&eacute;tait ces b&ecirc;tes l&agrave; : un peu avant l'arriv&eacute;e &agrave; l'abri de Ste-Lucie, Micka&euml;l &eacute;tabli un nouveau record de la travers&eacute;e arri&egrave;re du bateau, d&eacute;part l'int&eacute;rieur de la cabine, arriv&eacute;e la Gerbe (non ce n'est pas une commune du Finist&egrave;re), record qui va tenir pendant longtemps...<br/>
Au large de Ste-Lucie, 2 petites avaries pimentent cette fin d'apr&egrave;s-midi : <br/>
- un boot (drisse de grand voile) tombe &agrave; l'eau et se bloque sous le bateau.<br/>
- le moteur gauche nous fait une alarme batterie.<br/>
D'autre part, nous stressons un peu car nous n'apercevons pas une caille qui devrait pourtant se trouver l&agrave;. De nuit, c'est pas facile &agrave; rep&eacute;rer.<br/>
Nous arrivons &agrave; Marigot Bay aux environs de 20 heures, puis nous passons 1 heure &agrave; jeter l'ancre de secours, vu que le guindeau ne marche pas. 2 heures apr&egrave;s, on s'aper&ccedil;oit qu'on a d&eacute;riv&eacute; : une nouvelle bataille avec l'ancre est lanc&eacute;e car elle a l&acirc;ch&eacute;. Plus tard, longtemps plus tard Christophe R. fit part de ses inqui&eacute;tudes lors de cette premi&egrave;re nuit.<br/>
</p>

<table style='width:100%'><tr><td><h2>29/01/1997 : Marigot-Bay ==&gt; B&eacute;quia (l'initi&eacute; prononcera "B&eacute;cou&eacute;" afin de ne pas passer pour un rigolo)</h2></td><td align="right"><a class="travel2" href="#top"><img style="border:0px"  src="images/top_blue.png" alt="top"/></a></td></tr></table>
<p>
&Agrave; la traditionnelle question du matin (" et cette 1&egrave;re nuit "), les r&eacute;ponses sont diverses : cathy, seul, Jos&eacute;, seul et Micka&euml;l, seul, ont bien dormi. Les deux tourtereaux dormeurs ont respect&eacute; leurs convictions. Il est vrai qu'ils acceptent de se serrer et qu'aucun des 2 ne ronfle. Par contre Christophe R et Guillaume ne peuvent pas en dire autant (surtout Christophe), sans compter qu'ils ont jug&eacute; utile de mettre la t&ecirc;te au fond du lit, l&agrave; o&ugrave; il y a le moins de place et o&ugrave; &ccedil;a sent fort le gasoil. Il leur faudra deux jours pour r&eacute;agir malgr&eacute; les recommandations de Chrsitophe M.<br/>
C'est une journ&eacute;e de navigation tranquille, par comparaison &agrave; ce qu'on a v&eacute;cu la veille (d&eacute;part 7h30 c'est t&ocirc;t pour les Michaud. NDLR : c'&eacute;tait seulement pour la rime, toute ressemblance avec des faits ayant exist&eacute; ne serait que pure co&iuml;ncidence).<br/>
Le repas est pris au couvert de St-Vincent.<br/>
Nous arrivons &agrave; B&eacute;quia, l'entr&eacute;e des Grenadines &agrave; 17h30. La revanche de la bataille VATs-guindeau se d&eacute;roule plus calmement que la veille, l'exp&eacute;rience &eacute;tant de notre cot&eacute;. Cette fois-ci, on descend le guindeau principal &agrave; la main. Le cot&eacute; sport de la chose, c'est qu'il faut aussi le remonter &agrave; la main! Enfin, au bout de 2 ou 3 essais, le guindeau finit par c&eacute;der, apr&egrave;s s'&ecirc;tre n&eacute;anmoins vaillamment d&eacute;fendu. La belle est pr&eacute;vue pour le lendemain. (NDLR : mais non Cathy on ne parle pas de toi). Les premi&egrave;res baignades et sauts de Maxikakou ont lieu au mouillage.<br/>
</p>

<table style='width:100%'><tr><td><h2>30/01/1997 : B&eacute;quia =&gt; Mustique</h2></td><td align="right"><a class="travel2" href="#top"><img style="border:0px"  src="images/top_blue.png" alt="top"/></a></td></tr></table>
<p>
Le frigo est "en panne", 2 concombres, une boite de lardons, 2 ananas et un avocat sont perdus corps et &acirc;mes. Nous les pleurons un moment puis Magaly, remont&eacute;e comme jamais, &eacute;crit &agrave; son avocat (pas le fruit) afin d'assigner en justice le g&eacute;rant de la bo&icirc;te de location... &Agrave; peine a-t-elle pris son stylo multicolore &agrave; correcteur d'orthographe int&eacute;gr&eacute; qu'elle sombre dans un myst&eacute;rieux coma qui ne la quittera plus. Le sympt&ocirc;me le plus visible mais le plus silencieux : son corps allong&eacute; gisant sur la banquette du carr&eacute;.<br/>
De 9 &agrave; 11 heures, nous effectuons les formalit&eacute;s de douane et une ch'tite promenade dans B&eacute;quia. Apr&egrave;s d'&acirc;pres tergiversations pour un lot de tee-shirt, les n&eacute;gociations entre le repr&eacute;sentant de l'&eacute;quipage et la vendeuse locale ayant &eacute;chou&eacute;es, un nouveau sommet, cette fois-ci &agrave; Washington, est pr&eacute;vu courant avril. Les deux &eacute;missaires de l'O.VAT.U (Organisation des VAT Unis) sont d&eacute;sign&eacute;s &agrave; l'unanimit&eacute; et seront Christophe R et Guillaume.<br/>
Le d&eacute;part pour Mustique, par Petit Nevis, se fait tranquillement en tirant des bords. Pour f&ecirc;ter cette nouvelle victoire face &agrave; l'oc&eacute;an, Jos&eacute; lance par dessus bord sa casquette et Cathy l'oreiller gonflable de Guillaume. Le sus nomm&eacute; Guillaume commence &agrave; en avoir un peu marre que tout ce qui lui appartient finisse &agrave; la flotte, vu que le cache objectif de son appareil photo a suivi le m&ecirc;me chemin le jour pr&eacute;c&eacute;dent. Par souci du respect du secret de l'instruction, nous ne r&eacute;v&eacute;lerons pas ici le nom de la dormeuse suspect&eacute;e qui plaide non coupable, pour elle, le seul fautif est... le vent!<br/>
Vers 15 heures, nous arrivons &agrave; Mustique. &Ccedil;a commence &agrave; vraiment &ecirc;tre le paradis. Nous mouillons devant chez Mick Jagger et pourtant le fourbe ne nous invitera pas chez lui! Il faut dire que nous ne l'avions pas pr&eacute;venu de notre arriv&eacute;e.<br/>
Pour &eacute;viter tout probl&egrave;me avec le guindeau, nous pr&eacute;f&eacute;rons nous amarrer &agrave; une bou&eacute;e. La partie est remise au lendemain.<br/>
Christophe M, fan de plong&eacute;e et grand amateur de barrettes devant l'&eacute;ternel d&eacute;cide de flambouzer une peu pour &eacute;pater la Belle Au Bois Dormant :<br/>
Lui : " Regarde Magaly, je jette ta barrette dans l'eau et apr&egrave;s je vais la chercher! "<br/>
Elle : " Ne fais pas &ccedil;a, tu ne vas pas pouvoir la retrouver! "<br/>
Lui : " Mais si, regarde. " (sous entendu : " tu me prends pour un con ou quoi?)<br/>
Le plouf de la barrette fut suivi du glou-glou du Christophe qui plonge, qui cherche et qui ne trouve pas, m&ecirc;me avec l'aide de Micka&euml;l, plongeur &eacute;m&eacute;rite lui-m&ecirc;me.<br/>
Lui : " Euh... Magaly... On la trouve plus!.. " (Notez l'association de Micka&euml;l &agrave; son &eacute;chec.)<br/>
Elle : " Je te l'avais bien dit! "<br/>
Bref, les deux sont contents puisque Christophe, m&ecirc;me s'il a l'air d'un blaireau, s'est d&eacute;barrass&eacute; de la barrette encombrante, et Magaly a eu raison. De toutes fa&ccedil;ons, la joie de Christophe sera de courte dur&eacute;e puisque Magaly va trouver une autre barrette rapidement.<br/>
Cet &eacute;pisode fut suivi d'une promenade sur l'&icirc;le merveilleusement belle (de l'avis de Guillaume) et bien entretenue. Le Soir, une partie de l'&eacute;quipage part prendre une Pina Colada au Basil's Bar, Le bar de Mustique.
Le d&eacute;but de la nuit se passe &agrave; la belle &eacute;toile sur le filet pour Guillaume et Micka&euml;l Ka&euml;l qui de Breton(c) passe reporter pour CNN-international (il redeviendra Breton(c) au retour, &agrave; l'approche du canal de Ste-Lucie), au grand bonheur de Christophe R qui se dit qu'il va enfin pouvoir dormir tranquillement sans les ronflements intermittents de Guillaume. Ce bonheur ne va &ecirc;tre qu'&eacute;ph&eacute;m&egrave;re puisque Guillaume regagne la cabine car il a trop froid. Seul Micka&euml;l Ka&euml;l, en grand reporter qu'il est, va finir la nuit sur le filet. Il faut dire que 1) il est &eacute;quip&eacute; puisqu'il a un duvet et 2) &ccedil;a doit &ecirc;tre plus agr&eacute;able que de dormir en courbe sur la banquette du carr&eacute; (" non ", dixit Magaly)<br/>
</p>

<table style='width:100%'><tr><td><h2>31/01/1997 : Mustique =&gt; Tobago Cays =&gt; Palm Island</h2></td><td align="right"><a class="travel2" href="#top"><img style="border:0px"  src="images/top_blue.png" alt="top"/></a></td></tr></table>
<p>
Au petit matin un footing nous fait d&eacute;couvrir l'&icirc;le de Mustique, du moins pour les gar&ccedil;ons, puisque Magaly dort toujours et encore, tandis que Cathy est en retard (c'est bizarre, &ccedil;a ne lui arrive jamais, d'habitude elle a toujours une 1/2 heure d'avance...). Au retour, nous d&eacute;couvrons stup&eacute;fait que Micka&euml;l, pris d'une fringale subite au r&eacute;veil, a termin&eacute; la pur&eacute;e (fausse) Mousline (qui n'&eacute;tait d&eacute;j&agrave; pas tr&egrave;s bonne la veille, voire franchement beurk!). Les capacit&eacute;s estomacales et digestives du Breton nous &eacute;tonnerons toujours! Apr&egrave;s avoir pris un bon petit d&eacute;jeuner, baguettes et pains au chocolat frais, bon mais cher (24 FRS=1 baguette + 1 pain au chocolat), mais bons, mais chers..., et apr&egrave;s avoir donn&eacute; &agrave; manger au merle local, le d&eacute;part pour les Tobago Cays est donn&eacute;. En manoeuvrant, Guillaume se crame les doigts avec un boot qui part trop vite (et soit disant mal fix&eacute;, mais il faut toujours v&eacute;rifi&eacute; avant de faire une manoeuvre) et red&eacute;couvre les joies de la biafine ... Une corde, &ccedil;a chauffe! L'excuse pour ne pas faire de manoeuvres pendant trois jours est toute trouv&eacute;e (fain&eacute;ant!). De 12 &agrave; 16 heures, nous mouillons aux Tobago Cays. Plong&eacute;e sur la barri&egrave;re de corail et combat corps &agrave; corps avec un requin de plus de 5 m&egrave;tres sont au programme pour les Christophes, Guillaume et Micka&euml;l, ainsi que la s&eacute;ance photos traditionnelle de maxi cakos.<br/>
Palm Island est abord&eacute;e &agrave; 17 heures, c'est beau !!! (aussi). Ayant eu le temps de regarder un peu ce qui n'allait pas avec le guindeau, les VATs gagnent finalement la partie, au risque de se faire emporter une main; &agrave; chaque fois qu'ils l'utilisent, car il faut le descendre &agrave; la main, seule la remont&eacute;e fonctionnant, et ce gr&acirc;ce &agrave; une astuce de manipulation. Apr&egrave;s le beach volley, nous inventons le beach Scrabble sur Palm Island beach : on note les scores sur le sable. Tout fonctionne &agrave; merveille jusqu'&agrave; ce que Christophe M d&eacute;cide de faire l'&eacute;ponge et d'effacer les scores. Nous pouvons tout de m&ecirc;me souligner une victoire &eacute;crasante de Cathy qui, folle de joie, jette ses lunettes de soleil &agrave; la mer (sa "grinchosit&eacute;" l&eacute;gendaire ne tarda pas &agrave; remplacer sa "jouassit&eacute;"). Pour le coup les piles de l'appareil photo des Mich-A-Ud d&eacute;cident d'&ecirc;tre vide (" Honn&ecirc;tement, c'est pas d'pot! "). Suite &agrave; &ccedil;a, une soir&eacute;e tranquille s'annonce. Les amateurs (Micka&euml;l Ka&euml;l et Guillaume) battent les pros (Christophe R et Jos&eacute;) &agrave; la belote (comme quoi, la chance des d&eacute;butants existe vraiment). Belote qui sera suivi d'un Scrabble sans Jos&eacute;. Micka&euml;l Ka&euml;l repasse la nuit dehors, le frais (qui lui a manqu&eacute; durant le canal de Ste-lucie) lui r&eacute;ussit.<br/>
</p>

<table style='width:100%'><tr><td><h2>01/02/1997 : Palm Island =&gt; Union =&gt; Morpion =&gt; Petit St-Vincent</h2></td><td align="right"><a class="travel2" href="#top"><img style="border:0px"  src="images/top_blue.png" alt="top"/></a></td></tr></table>
<p>
Un quart d'heure de navigation et nous nous retrouvons &agrave; Union (Clifton Harbourg). De 9 h 30 &agrave; 11 H, nous nous promenons dans la "ville", et achetons quelques cartes postales et autres souvenirs (pour les tee-shirts, nous notons une bonne n&eacute;gociation men&eacute;e par Guillaume, qui aboutit &agrave; un prix d&eacute;fiant toute concurrence. Tout &agrave; sa joie, Guillaume oublie de r&eacute;cup&eacute;rer sa monnaie. Oubli qui sera r&eacute;parer par la suite). A Union, il n'y a absolument rien &agrave; voir mais il faut signaler 2 choses : - des requins Magaly (serait-elle aussi avide de chair humaine qu'eux?) dormeurs nous accueillent dans un bassin &agrave; l'entr&eacute;e du port, - il n'y a pas de pile pour l'appareil de dormeur Magaly et Christophe ! Nous abordons Morpion &agrave; l'heure de l'ap&eacute;ro !!! Tout le monde se sent oblig&eacute; d'arroser tous les ports, pass&eacute;s ou &agrave; venir, ceux &agrave; l'&eacute;tat de projet ou ceux que nous ne visiterons jamais... Sur cet &icirc;lot, un incident diplomatique grave manque se produire : un anglais &agrave; qui nous demandons de nous prendre en photo (la photo est d'ailleurs r&eacute;ussie) et &agrave; qui nous offrons un ti-punch, se permet de nous dire que c'est bon alors qu'il balance son verre (du Neisson!). D&eacute;cid&eacute;ment, on ne pourra jamais s'entendre avec les rosbifs. Suite &agrave; &ccedil;a, nous voguons pour Petit St-Vincent que nous atteignons &agrave; 15H15. Repos (bien m&eacute;rit&eacute;) et plein d'eau (pour le bateau &eacute;videmment. D'ailleurs, 800 litres pour un bateau qui ne peut en contenir que 500, &ccedil;a fait beaucoup. Les habitants locaux ont le sens des affaires !). De 17h &agrave; 18h, pendant que certains font des emplettes, d'autres en profitent pour visiter l'&icirc;le. Scrabble et belote sont au programme du soir. Les d&eacute;butant ont toujours un pot de pendu.<br/>
</p>

<table style='width:100%'><tr><td><h2>02/02/1997 : Petit St-Vincent =&gt; Saline Bay (Mayerau) =&gt; Salt Whistle Bay (Mayerau)</h2></td><td align="right"><a class="travel2" href="#top"><img style="border:0px"  src="images/top_blue.png" alt="top"/></a></td></tr></table>
<p>
8 est le chiffre de ce d&eacute;but de journ&eacute;e : cela fait 8 ans que Magaly et Christophe se connaissent (quel courage (pour qui?)). Cela fait 8 mois que nous (les autres) les connaissons, soit en "temps Michaud" (= TM) environ 8 heures. (TM=TR x 10%-Tafdb) (NDLR : TR*10%=2*TE, TE=temps &eacute;veil moyen par demi-journ&eacute;e pour une personne dormant normalement, Tafdb=Temps &agrave; faire des b&eacute;b&eacute;s.)
8 est aussi le nombre d'&eacute;tapes qu'il faut en moyenne pour qu'un Breton(c) ram&egrave;ne l'annexe apr&egrave;s le footing du petit matin :<br/>
1 - Je pars chercher les rigolos qui sont rester sur l'&icirc;le.<br/>
2 - Damned, je cale.<br/>
3 - J'essaie tant bien que mal de red&eacute;marrer (fais ch...!).<br/>
4 - Puisque je n'y arrive pas, je rame.<br/>
5 - Finalement, je nage, &ccedil;a va plus vite.<br/>
6 - Je demande de l'aide.<br/>
7 - Merci Christophe M.<br/>
8 - Je suis de retour.<br/>
Nous partons pour Mayereau &agrave; 9H45 que nous atteignons &agrave; 11H, plus exactement &agrave; Saline Bay. Promenade et photos des Tobago Cays qui ne sont qu'&agrave; quelques brass&eacute;es de l&agrave; sont de nouveau au programme pour tout le monde. Nous repartons pour un second mouillage, Salt Whistle Bay, tr&egrave;s joli voir m&ecirc;me paradisiaque (ce qui ne change pas grand-chose par rapport aux autres jours), o&ugrave; nous passerons la nuit. Le repas pris, nous nous retrouvons tous sur la plage ou dans le hamac (quand celui-ci n'est pas squatt&eacute; par des &eacute;trangers importuns). Repos et beach Scrabble suivront pour finir l'apr&egrave;s-midi. Christophe M, ayant finalement assimil&eacute; la technique dite des 'scores dans le sable', s'abstient de faire l'&eacute;ponge (et gagne). Le soir une Pina Colada est la bienvenue. Magaly ne se couche pas aussi t&ocirc;t que d'habitude car elle est prise (en tout bien tout honneur) d'un fou rire convulsif nerveux caract&eacute;ristique chez elle d'une prise trop rapide d'un d&eacute; &agrave; coudre d'alcool. Les accros de la Belote et du Scrabble se coucheront vers 3 heures.<br/>
</p>

<table style='width:100%'><tr><td><h2>03/02/1997 : Mayereau =&gt; B&eacute;quia</h2></td><td align="right"><a class="travel2" href="#top"><img style="border:0px"  src="images/top_blue.png" alt="top"/></a></td></tr></table>
<p>
Nous effectuons la travers&eacute;e en 4h30, en partant &agrave; 10h. Pendant la navigation un &eacute;norme barracuda (disons plut&ocirc;t un barracuda) est tomb&eacute; dans les mailles de nos filets (disons plut&ocirc;t a mordu le crochet de notre ligne). Quelques heures plus tard (le soir), le barracuda cuit dans le four d&eacute;gageant une odeur de bonne humeur (merci Cathy et Jos&eacute;) !!! L'apr&egrave;s-midi, &ccedil;a sent le d&eacute;j&agrave; vu (et la fin du voyage) puisque nous nous retrouvons &agrave; la douane apr&egrave;s avoir fait le plein de gasoil. Le d&eacute;jeuner est pris &agrave; 16h (durant toute la croisi&egrave;re, on a &eacute;t&eacute; un tantinet d&eacute;cal&eacute; dans nos horaires) et une promenade digestive dans Port Elizabeth suit. Le soir, tard le soir, Christophe M et Guillaume accompagnent Cathy &agrave; une cabine t&eacute;l&eacute;phonique en tant que garde du corps. Ils ne se remettront que difficilement de cette &eacute;prouvante &eacute;preuve, la violence sourde qui se d&eacute;gage de l'atmosph&egrave;re silencieuse mais n&eacute;anmoins mena&ccedil;ante de B&eacute;quia les a en effet fortement marqu&eacute;es. On peut noter aussi un fait remarquable : nous faisons une soir&eacute;e tarot &agrave; 5 personnes, toutes des VATs, ce qui veut dire que, fait exceptionnel, Magaly est encore en &eacute;veil !!! Lors de cette soir&eacute;e nous (surtout les Michauds) avons pu aborder le th&egrave;me du "roi au 1er tour". Ce vaste sujet (enfin, surtout vaste pour Magaly parce qu'il n'y a vraiment rien de compliqu&eacute; l&agrave; dedans : on ne fait pas d'entr&eacute;e du fond sauf si on est avec celui qui a pris) devra faire l'objet d'une prochaine rencontre puisqu'aucune solution viable n'a pu &ecirc;tre d&eacute;gag&eacute;e.<br/>
</p>

<table style='width:100%'><tr><td><h2>04/02/1997 : B&eacute;quia =&gt; Le Marin (ou : 'Le Jour Le Plus Long')</h2></td><td align="right"><a class="travel2" href="#top"><img style="border:0px"  src="images/top_blue.png" alt="top"/></a></td></tr></table>
<p>
D&eacute;part de B&eacute;quia &agrave; 7h00, d&egrave;s les premi&egrave;res secousses, Cathy ne peut s'emp&ecirc;cher de rafra&icirc;chir son matelas en oubliant (mais est-ce r&eacute;ellement un oubli?) de fermer sa fen&ecirc;tre alors qu'on se prend des paquets de mer. C'est Micka&euml;l qui est content, il ne dormira pas seul dans le carr&eacute;. 8h15, St Vincent. 9h15, un seau &agrave; la mer, suivi d'un saut &agrave; la mer. N'&eacute;coutant que son courage l&eacute;gendaire, Christophe (celui qui ne dort pas, sauf le matin) se retrouve derri&egrave;re le bateau &agrave; faire du sauvetage de seau, vu que Guillaume, m&ecirc;me arm&eacute; d'une gaffe, ne sait rien faire de ses mains et a d&eacute;j&agrave; loup&eacute; deux fois le seau. Enfin, Jos&eacute; r&eacute;cup&egrave;re le sot &agrave; la mer. Justification des seuaoauts &agrave; la mer : (miraculeusement, et une fois n'est malheureusement pas coutume) un poisson mord &agrave; la ligne. Apr&egrave;s avoir remont&eacute; le susdit poisson sur le bateau, Micka&euml;l se charge de nettoyer le pont &agrave; grand coups d'eau (qui venait du seau). Sa t&acirc;che termin&eacute;e, le Breton(c) de service d&eacute;tache le seau du boot et, avec la maladresse qui le caract&eacute;rise si bien, il envoie n&eacute;gligemment le seau prendre un bain. L'alerte est donn&eacute;e. Jos&eacute; fait faire demi-tour au bateau; alors que Guillaume sort la gaffe afin de gaffer (il a r&eacute;par&eacute; ses mains br&ucirc;l&eacute;es au troisi&egrave;me degr&eacute; par le boot). Micka&euml;l remonte la ligne afin qu'elle ne se prenne pas dans les h&eacute;lices des moteurs. L&agrave;, tout s'acc&eacute;l&egrave;re (le suspens devient haletant !) puisqu'un second poisson mord. Nous saurons plus tard qu'il s'agit d'une bonite. D'o&ugrave;, gaffes de Guillaume, saut de Christophe (hyper content pour la circonstance de prendre un bain...), et joie de Jos&eacute; d'avoir pris une bonite (et d'&ecirc;tre entour&eacute; d'un si bon &eacute;quipage !).<br/>
10h45, nous quittons St Vincent (avec 2 poissons de plus, un seau v&eacute;, et un Christophe mouill&eacute;).<br/>
15h00, nous arrivons &agrave; Ste Lucie apr&egrave;s une travers&eacute;e sans probl&egrave;mes. L&agrave;, oh joie, stup&eacute;faction, admiration et &eacute;bahissement, ce fut la s&eacute;quence '&Eacute;motion' puisque des dauphins nous ont fait l'honneur de venir nous accompagner (apr&egrave;s nous avoir superbement ignor&eacute;s &agrave; l'aller).<br/>
Vers 17h00, nous d&eacute;cidons de manger (des raviolis) avant d'attaquer la travers&eacute;e du canal. Les raviolis engloutis, Magaly d&eacute;cide de faire une mousse au chocolat, &agrave; peine a-t-elle commenc&eacute; (et &agrave; peine Guillaume a-t-il commenc&eacute; &agrave; battre les blancs en neige) que nous abordons le canal. &Ccedil;a bouge! Guillaume abandonne son poste de batteur tandis que Magaly fait fondre le chocolat. L'odeur est trop forte pour Micka&euml;l qui retrouve son statut de Breton(c) et bat son propre record de travers&eacute;e du pont arri&egrave;re pour terminer par app&acirc;ter les poissons avec des raviolis. Il sera suivi peu apr&egrave;s par Christophe M. Pour les autres, le voyage se passe. Ni tr&egrave;s bien ni tr&egrave;s mal. Guillaume n'est pas loin de faire une tentative pour battre le record mais se ressaisit &agrave; temps. La travers&eacute;e dans la nuit est assez impressionnante vu qu'on ne voit pas arriver les vagues. Bref, c'est 3h30 de folie.<br/>
&Agrave; 22h00 nous arrivons au Marin o&ugrave; nous d&eacute;gustons les poissons avant de faire un ch'tit Scrabble pendant lequel Guillaume s'endort &agrave; chaque tour.<br/>
Il est &agrave; noter que la mousse au chocolat ne sera jamais finie et terminera sa carri&egrave;re avort&eacute;e pour partie dans le ventre de Christophe M et pour partie dans la poubelle.<br/>
</p>

<table style='width:100%'><tr><td><h2>05/02/1997 : Le Marin =&gt; Pointe du Bout</h2></td><td align="right"><a class="travel2" href="#top"><img style="border:0px"  src="images/top_blue.png" alt="top"/></a></td></tr></table>
<p>
Il s'agit d'une matin&eacute;e de navigation tout ce qu'il y a de plus tranquille. On passe pr&egrave;s du Diamant puis Guillaume peut faire le beau &agrave; la barre &agrave; naviguer entre les cailles.<br/>
<br/>
<br/>
Bref, c'&eacute;tait super et on repartirait bien pour une autre dizaine de jours, dans les &Icirc;les Vierges par exemple!<br/>
</p>

<?php
	GetAllImagesFromCountry( 9 );

	EndOfPage( 'fre' );
?>

</body>
</html>
